### ISSUE TITLE
SE Jurisdiction - game logo gets truncated from top bar on resizing game

### ISSUE THREAD

**Issue by vinitanolimit** [nolimitcity/nolimit.js#23]
launched the game on desktop iFrame

![Screen Shot 2020-06-09 at 1 18 23 PM](https://user-images.githubusercontent.com/49147700/84131504-40dd8e00-aa62-11ea-93d4-53fa34c2d79e.png)

**Comment by rebecka01** [comment]
Before we didn't show these for desktop (only for mobile)
but now when we changed the logos (I think it was), this changed and we see the it when it is sent in (both mobile and desktop)
It was said to let it be since on desktop operators have their own links and shouldn't send the links/events.

@emil-nolimitcity Can/should we rely on that operators doesn't send in Swedish links/events for desktop?
Or should we change back so that it is not displayed for desktop (even if sent in), or adjust so that game doesn't get cut off?

**Comment by emil-nolimitcity** [comment]
Internal problem in our fake site not a real issue closing this.
