### ISSUE TITLE
Release/deploy 1.2.86 to prod on the 5th of November.  Re-open due to NPM-question

### ISSUE THREAD

**Issue by rebecka01** [nolimitcity/nolimit.js#77]
Release/deploy 1.2.86 to prod on the 5th of November

Today we have 1.2.85

This is to release the new loaders Labs/Over the limit etc. 
For more background, see https://github.com/nolimitcity/loader/issues/135

There are three parts to get this working in prod:

- loader.js (+html etc),
- nolimit.js
- the games

The loader is already out in prod, and some of the games. So last step is to release the last nolimit.js to prod. 

You might want to discuss with Malcolm regarding what time we should do this. Since biz wants to make a happening out of this :)

**Comment by grunka** [comment]
The thing that needs to be done for nolimit.js is to publish the committed version 1.2.86 as the latest. Since everything is committed the only thing needed to be run is this from a check out of this repository:

```shell
npm run www
```

Due to how it works an install and/or build is not necessary as it has already been done. Doing a full build will create another new version and this we don't want. This command will "simply" promote the checked in version to be the latest one in the gh-pages branch.

More details for the curious can be found in DEVELOPMENT.md and/or the scripts included in package.json

**Comment by bucht** [comment]
Pushed out to production now before the morning release

**Comment by rebecka01** [comment]
@bucht Can you help out? 
Hevar needs help in https://github.com/nolimitcity/replay-frontend/issues/1427

> We also have https://www.npmjs.com/package/@nolimit/nolimit.js which is still on v. 1.2.85

**Comment by rebecka01** [comment]
I think Hevar solved it via using CDN instead.
Do we know if we have customers using npm? 
What do we do with the npm-problem? Wait for John or is there something we should/can do? @bucht

**Comment by rebecka01** [comment]
In today's meeting Bucht said it is better to wait for John. 
so I'm reassigning this one to you @grunka

**Comment by grunka** [comment]
I've deployed the latest version to "@nolimitcity/nolimit.js", I've also deprecated the package at "@nolimit/nolimit.js" since that is no longer possible to properly update since the org name does not match the github repository.

Have also noted in the readme that the last version we will deploy to the npmjs repository is this one since it's not really a good way of distributing this library since we really want people to use the cdn version.

**Comment by rebecka01** [comment]
Spoke with John yesterday about this one
not so much to test
and the rest is out in prod since long so I'll remove this one from the project (and also add the verified ok since we haven't heard of any problems).
